### PR TITLE
Link to .md files in ./pages.

### PR DESCRIPTION
**Pull request by AntoineStevan**
Linking to a file only with its name appears to be insufficient if the search has to be recursive.
Maybe there is a way to force a recursive search of files in the repo, the easiest solution I found was to add the path.

Namely **adding `pages/` in front and `.md` after links to pages** in the table of content of the repo.

However, I couldn't find the Altair page anywhere in the repo, so there is still an error at this line.

### CODE REVIEW

**Comment by xoolive** [comment]
I don't really get your problem, but if it's better on your side and since it doesn't seem to break anything here, I'll merge it...

**Comment by AntoineStevan** [comment]
I added a comment on one of the lines.

It is strange that you do not see the 404 page. It is still the case with the Altair chapter, maybe you could try to see the difference with, for instance, the numpy chapter :-)

**Comment by xoolive** [comment]
All links on this page work, right? https://www.xoolive.org/pyseminar/

**Comment by AntoineStevan** [comment]
yes they do!
i am talking about the github repository side of this. this is where things did not work

**Pull request merged**
